name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK in Docker
        uses: docker://ghcr.io/kivy/buildozer:master
        with:
          args: android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-App
          path: bin/*.apk
