name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # إعطاء صلاحيات الكتابة مباشرة من الكود
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer
        run: |
          pip install --user --upgrade buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          # هذا الأمر يوافق على كل الرخص ويجبر البناء
          yes | buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-App
          path: bin/*.apk
